export const PRODUCTION_PANEL_CONFIGS = {
  "text-micro": {
    id: "text-micro",
    name: "Text / Micro post",
    title: "Short-form post",
    accentToken: "#22c55e",
    requiredOutputs: [
      { id: "hook", label: "Hook line", required: true },
      { id: "value", label: "Value prop", required: true },
      { id: "cta", label: "CTA to /go/* or Calendly", required: true },
    ],
    actions: ["Copy prompt", "Open platform", "Paste published URL"],
    ctaPlacementDefault: "End of post",
    publishedProofMode: "url",
    fields: [
      { id: "hook", label: "Hook" },
      { id: "body", label: "Body", multiline: true },
      { id: "cta_copy", label: "CTA copy" },
    ],
  },
  thread: {
    id: "thread",
    name: "Thread",
    title: "Thread / carousel text",
    accentToken: "#d4af37",
    requiredOutputs: [
      { id: "tweets", label: "5–7 parts", required: true },
      { id: "proof", label: "Proof from /works", required: false },
    ],
    actions: ["Copy prompt", "Open platform", "Paste published URL"],
    fields: [{ id: "thread_draft", label: "Thread draft", multiline: true }],
  },
  "article-longform": {
    id: "article-longform",
    name: "Article",
    title: "Long-form article",
    accentToken: "#7dd3a8",
    requiredOutputs: [{ id: "draft", label: "Draft link or slug", required: true }],
    actions: ["Open newsletter editor", "Open platform", "Paste published URL"],
    fields: [
      { id: "title", label: "Title" },
      { id: "excerpt", label: "Excerpt", multiline: true },
    ],
  },
  newsletter: {
    id: "newsletter",
    name: "Newsletter",
    title: "Newsletter issue",
    accentToken: "#22c55e",
    requiredOutputs: [
      { id: "subject", label: "Subject line", required: true },
      { id: "excerpt", label: "Excerpt", required: true },
    ],
    actions: ["Open newsletter editor", "Paste published URL"],
    fields: [{ id: "issue_notes", label: "Issue notes", multiline: true }],
  },
  "image-infographic": {
    id: "image-infographic",
    name: "Image",
    title: "Image / infographic",
    accentToken: "#d4af37",
    requiredOutputs: [{ id: "asset", label: "Image asset", required: true }],
    actions: ["Copy brief", "Open platform", "Paste published URL"],
    fields: [{ id: "visual_brief", label: "Visual brief", multiline: true }],
  },
  "story-status": {
    id: "story-status",
    name: "Story",
    title: "Story / status",
    accentToken: "#22c55e",
    requiredOutputs: [{ id: "frames", label: "Story frames", required: true }],
    actions: ["Open platform", "Paste published URL"],
    fields: [{ id: "story_copy", label: "Story copy", multiline: true }],
  },
  "short-video": {
    id: "short-video",
    name: "Short video",
    title: "Short video / reel",
    accentToken: "#d4af37",
    requiredOutputs: [{ id: "script", label: "30–60s script", required: true }],
    actions: ["Copy script", "Open platform", "Paste published URL"],
    fields: [{ id: "script", label: "Script", multiline: true }],
  },
  "long-video": {
    id: "long-video",
    name: "Long video",
    title: "Long-form video",
    accentToken: "#7dd3a8",
    requiredOutputs: [{ id: "outline", label: "Outline", required: true }],
    actions: ["Copy outline", "Open platform", "Paste published URL"],
    fields: [{ id: "outline", label: "Outline", multiline: true }],
  },
  "broadcast-community": {
    id: "broadcast-community",
    name: "Community",
    title: "Community post",
    accentToken: "#a3a3a3",
    requiredOutputs: [{ id: "post", label: "Post body", required: true }],
    actions: ["Copy prompt", "Open platform", "Paste published URL"],
    fields: [{ id: "post_body", label: "Post body", multiline: true }],
  },
  "indexing-syndication": {
    id: "indexing-syndication",
    name: "Syndication",
    title: "Syndication / indexing",
    accentToken: "#7dd3a8",
    requiredOutputs: [
      { id: "canonical", label: "Canonical URL", required: true },
      { id: "sitemap", label: "Sitemap / llms.txt check", required: false },
    ],
    actions: ["Open platform", "Paste published URL"],
    fields: [{ id: "syndication_notes", label: "Notes", multiline: true }],
  },
};

export function getPanelConfig(panelId) {
  return PRODUCTION_PANEL_CONFIGS[panelId] || PRODUCTION_PANEL_CONFIGS["text-micro"];
}
